sonar.projectKey=cohort-9-mern-9541-amna
sonar.projectName=cohort-9-mern-9541-amna
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=node_modules/**,SonarCubeReport/**,.env,coverage/**